controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_candidature_new:
    path: /candidature/new/{id}
    controller: App\Controller\CandidatureController::new
